# Site settings
title: 흩어진 편린들의 모이는 곳
description: 삶 좀 편해지고싶은 사람의 개인 블로그입니다.
email: wwponv158@gmail.com
baseurl: 
url: "http://meigoarisa.github.io" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png

#feed
feedburner_username:
#twitter
twitter_username:
github_username: 

#linkedin
linkedin_username: 

#google analytics
google_analytics_id : 
#gplus
gplus_username: 

#fb_username
fb_username:

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name: xxx
disqus-shortname: xxx
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  pranavrajs:
    display_name: kanghyune kim
    email: wwponv158@gmail.com
    fb: 
    linkedin: 
    twitter: 
    github: https://github.com/MeigoArisa/
